import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_BASE = import.meta.env.VITE_API_BASE || 'http://127.0.0.1:8000';
const pages = ['Home', 'How it works', 'Try the predictor', 'Sample result', 'Model & science', 'About'];
const models = [
  ['Random Forest', 'balanced, fast'],
  ['XGBoost', 'highest accuracy'],
  ['Support Vector Regression (SVR)', 'smooth estimates'],
  ['Gaussian Process Regression (GPR)', 'gives confidence range'],
];
const fallbackPresets = [
  { id: 'aspirin-abl1', drug_name: 'Aspirin', target_name: 'ABL1', smiles: 'CC(=O)OC1=CC=CC=C1C(=O)O', sequence: '', description: 'Aspirin paired with ABL1 for the sample result flow.' },
];

async function getJson(path) {
  const response = await fetch(`${API_BASE}${path}`);
  if (!response.ok) throw new Error('The service could not load this content.');
  return response.json();
}

async function postJson(path, payload) {
  const response = await fetch(`${API_BASE}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.detail || 'The request could not be completed.');
  return body;
}

function BrandMark() {
  return <svg className="brand-mark" viewBox="0 0 30 30" fill="none" aria-hidden="true"><circle cx="9" cy="15" r="5" fill="#1F6F63"/><circle cx="21" cy="9" r="4" fill="#DE9A34"/><circle cx="21" cy="21" r="4" fill="#DE9A34" opacity=".55"/><line x1="9" y1="15" x2="21" y2="9" stroke="#12201F" strokeWidth="1.4"/><line x1="9" y1="15" x2="21" y2="21" stroke="#12201F" strokeWidth="1.4" opacity=".5"/></svg>;
}

function Eyebrow({ children }) { return <div className="eyebrow">{children}</div>; }
function ActionButton({ children, onClick, ghost = false, className = '' }) { return <button className={`btn ${ghost ? 'btn-ghost' : 'btn-primary'} ${className}`} onClick={onClick}>{children}</button>; }

function HeroVisual() {
  return <div className="hero-visual"><svg viewBox="0 0 380 220" aria-label="Drug and kinase binding illustration">
    <style>{`@keyframes dtiFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}} @keyframes dtiWiggle{0%,100%{transform:rotate(0)}25%{transform:rotate(-3deg)}75%{transform:rotate(3deg)}} @keyframes dtiDash{to{stroke-dashoffset:-24}} .hero-key{animation:dtiFloat 3.2s ease-in-out infinite}.hero-kinase{animation:dtiWiggle 4.5s ease-in-out infinite;transform-origin:290px 110px}.hero-path{stroke-dasharray:6 6;animation:dtiDash 1.4s linear infinite}`}</style>
    <g className="hero-key"><circle cx="95" cy="110" r="46" fill="#E4EFEA" stroke="#1F6F63" strokeWidth="2"/><path d="M75 96l14 14-14 14" stroke="#1F6F63" strokeWidth="4" fill="none" strokeLinecap="round" strokeLinejoin="round"/><circle cx="95" cy="110" r="9" fill="#1F6F63"/></g>
    <text x="95" y="172" textAnchor="middle" fontFamily="IBM Plex Mono" fontSize="11" fill="#5B655F">drug (SMILES)</text><path className="hero-path" d="M155 110h60" stroke="#DE9A34" strokeWidth="2"/><text x="185" y="98" textAnchor="middle" fontFamily="Space Grotesk" fontSize="11" fill="#B87A1F">binds?</text>
    <g className="hero-kinase"><rect x="245" y="70" width="90" height="80" rx="12" fill="#FCEFDD" stroke="#DE9A34" strokeWidth="2"/><path d="M270 110q20-26 40 0-20 26-40 0z" fill="none" stroke="#B87A1F" strokeWidth="2.5"/></g><text x="290" y="172" textAnchor="middle" fontFamily="IBM Plex Mono" fontSize="11" fill="#5B655F">kinase (protein)</text><text x="190" y="30" textAnchor="middle" fontFamily="Space Grotesk" fontWeight="600" fontSize="13" fill="#12201F">Affinity score = how tightly it fits</text>
  </svg></div>;
}

const pipeline = [
  ['01', 'Read the drug & protein', 'The drug is written as a text code (SMILES); the protein as its amino-acid sequence. No 3D lab data needed.'],
  ['02', 'Turn them into numbers', 'Chemistry software converts each into structured features — shape, composition, physical properties.'],
  ['03', 'Ask the model', 'Four different ML algorithms independently estimate how strong the interaction is.'],
  ['04', 'Explain the answer', 'The tool shows not just a score, but which features pushed it up or down.'],
];
const whyCards = [
  ['clock', 'Faster than lab testing', 'Screening a candidate drug computationally takes seconds. Testing it physically can take weeks and real money.'],
  ['shield', 'Honestly evaluated', <>We test on drugs and proteins the model has <b>never seen before</b> — not just shuffled copies of its training data.</>],
  ['signal', 'Not a black box', 'Every prediction comes with a plain-language reason, so the “why” is never hidden behind the score.'],
];

function CardIcon({ type }) {
  if (type === 'clock') return <svg className="icon" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="#1F6F63" strokeWidth="2"/><path d="M12 7v5l3 3" stroke="#1F6F63" strokeWidth="2" strokeLinecap="round"/></svg>;
  if (type === 'shield') return <svg className="icon" viewBox="0 0 24 24" fill="none"><path d="M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7l8-4z" stroke="#DE9A34" strokeWidth="2"/></svg>;
  return <svg className="icon" viewBox="0 0 24 24" fill="none"><path d="M4 12h4l2-7 4 14 2-7h4" stroke="#B84B3A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}

function HomePage({ navigate }) {
  return <div className="page active"><div className="hero"><div><Eyebrow>VTU Major Project · AI &amp; Data Science</Eyebrow><h1>Predicting whether a drug <em>fits</em> its target — before it's ever tested in a lab.</h1><p className="lede">Feed it a drug and a protein. It predicts how tightly they'd bind — tested only on pairs it's never seen before.</p><div className="hero-actions"><ActionButton onClick={() => navigate('Try the predictor')}>Try a prediction →</ActionButton><ActionButton ghost onClick={() => navigate('How it works')}>What does this actually mean?</ActionButton></div></div><HeroVisual/></div><section><Eyebrow>The pipeline, in four steps</Eyebrow><div className="pipeline">{pipeline.map(([num, title, desc]) => <div className="pstep" key={num}><div className="num">{num}</div><h3>{title}</h3><p>{desc}</p></div>)}</div></section><section><Eyebrow>Why this matters</Eyebrow><div className="grid-3">{whyCards.map(([icon, title, copy]) => <div className="card" key={title}><h3><CardIcon type={icon}/>{title}</h3><p>{copy}</p></div>)}</div></section></div>;
}

const terms = [
  ["What's a kinase?", <>A kinase is a protein that acts like a molecular <b>switch</b> — it turns other proteins on or off inside a cell. When kinases misfire, cells can grow uncontrollably, which is why they're one of the most important drug targets in cancer treatment.</>, 'a light switch. The wrong drug flips it the wrong way; the right drug holds it exactly where you want it.'],
  ["What's “binding affinity”?", "It's a number describing how strongly a drug molecule sticks to its target protein. Higher affinity generally means the drug is more effective at that target — and less likely to need a huge dose.", 'how snugly a key fits a lock. A loose fit barely turns it; a snug fit works reliably.'],
  ['Why “cold-split” evaluation?', 'Most simple tests let a model see similar drugs or proteins during both training and testing — which makes it look smarter than it is. A cold split removes that overlap entirely, so the reported accuracy reflects real-world performance on drugs it has genuinely never encountered.', 'testing a student on questions from a totally different textbook, not the one they studied from.'],
  ['What is SHAP, and why show it?', 'SHAP is a method that scores how much each input feature (a molecule shape, a protein property) pushed the final prediction up or down. Instead of trusting the model blindly, you can see exactly what it “noticed.”', 'a teacher showing their working, not just the final answer on the exam.'],
];
const modelDescriptions = [
  ['Random Forest', 'Many decision trees voting together. Robust, hard to fool, good default baseline.'],
  ['XGBoost / LightGBM', "Trees built one after another, each correcting the last one's mistakes. Usually the most accurate."],
  ['Support Vector Regression', 'Finds the smoothest boundary that still respects the data. Good with smaller, cleaner feature sets.'],
  ['Gaussian Process', 'Slower, but tells you how confident it is in each prediction — not just the number itself.'],
];
function HowPage() { return <div className="page active"><section className="page-intro"><Eyebrow>Plain-language explainer</Eyebrow><h2>Five terms this project relies on — explained without the jargon</h2><p className="lede">You don't need a biology background to follow this. Here's every technical term on this site, explained once, properly.</p></section><div className="grid-2">{terms.map(([title, body, analogy]) => <div className="card" key={title}><h3>{title}</h3><p>{body}</p><div className="analogy"><b>Think of it as:</b> {analogy}</div></div>)}</div><section><Eyebrow>The four models we compare</Eyebrow><p className="lede">Rather than picking one algorithm and hoping it's right, this project trains four different classical ML models on the exact same data, so their strengths and weaknesses can be compared directly.</p><div className="grid-3 model-grid">{modelDescriptions.map(([title, desc]) => <div className="card" key={title}><h3>{title}</h3><p>{desc}</p></div>)}</div></section></div>; }

function PredictorPage({ presets, onPrediction, navigate }) {
  const [preset, setPreset] = useState(null);
  const [smiles, setSmiles] = useState('CC(=O)OC1=CC=CC=C1C(=O)O');
  const [sequence, setSequence] = useState('');
  const [model, setModel] = useState('Random Forest');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const choosePreset = (value) => { setPreset(value); setSmiles(value.smiles); setSequence(value.sequence); setError(''); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await postJson('/api/predict', { smiles, protein_sequence: sequence, model, drug_name: preset?.drug_name || 'Custom drug', target_name: preset?.target_name || 'Custom target' }); onPrediction(result); navigate('Sample result'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="page active"><section className="page-intro"><Eyebrow>Interactive demo</Eyebrow><h2>Try a prediction</h2><p className="lede">Pick a real example, or paste your own. No chemistry knowledge needed — the dropdowns give you known drugs and kinases to start with.</p></section><div className="try-layout"><form className="panel" onSubmit={submit}><div className="field"><label htmlFor="drug">Drug molecule <span className="helptext">— as a SMILES string</span></label><textarea id="drug" value={smiles} onChange={(event) => setSmiles(event.target.value)} placeholder="e.g. CC(=O)OC1=CC=CC=C1C(=O)O"/><div className="example-row">{presets.filter((item) => item.drug_name !== 'Custom drug').slice(0, 3).map((item) => <button type="button" className="chip" key={item.id} onClick={() => choosePreset(item)}>{item.drug_name}</button>)}<button type="button" className="chip" onClick={() => { setPreset(null); setSmiles(''); }}>Paste my own …</button></div></div><div className="field"><label htmlFor="protein">Target protein <span className="helptext">— kinase sequence</span></label><textarea id="protein" value={sequence} onChange={(event) => setSequence(event.target.value)} placeholder="e.g. MKTAYIAKQR…"/><div className="example-row">{presets.filter((item) => item.target_name).slice(0, 2).map((item) => <button type="button" className="chip" key={item.id} onClick={() => choosePreset(item)}>{item.target_name} ({item.target_name === 'ABL1' ? 'leukemia' : 'lung cancer'})</button>)}<button type="button" className="chip" onClick={() => { setPreset(null); setSequence(''); }}>Paste my own …</button></div></div><div className="field"><label>Model</label><div className="model-select">{models.map(([name, note]) => <button type="button" className={`model-opt ${model === name ? 'selected' : ''}`} key={name} onClick={() => setModel(name)}><span className="mname">{name === 'Support Vector Regression (SVR)' ? 'SVR' : name.replace(' Regression (GPR)', '')}</span><span className="mnote">{note}</span></button>)}</div></div>{error && <div className="form-error" role="alert">{error}</div>}<ActionButton className="full-width">{busy ? 'Computing prediction…' : 'Predict binding affinity →'}</ActionButton><div className="mini-note"><span>ⓘ</span><span>This model was trained on the KIBA benchmark dataset (~118K measured drug–kinase pairs) and tested on kinases and drugs it never saw during training.</span></div></form><div className="panel after-panel"><h3>What happens after you click predict</h3>{['Your SMILES and sequence are converted into the same numeric features the model was trained on.', 'The selected model estimates a KIBA affinity score for this exact pair.', 'SHAP identifies which specific features drove that score up or down.', 'You get a plain-language readout — not just a raw number.'].map((text, index) => <div className="after-step" key={text}><div className="mono step-number">{index + 1}</div><div>{text}</div></div>)}</div></div></div>;
}

function DockingScene({ result }) {
  const [replay, setReplay] = useState(0);
  const target = result?.target?.name || 'ABL1';
  return <div className="dock-scene"><div className="dock-caption" key={replay}>Approaching {target}…</div><svg viewBox="0 0 380 140" className="dock-svg" aria-label="Animated docking scene"><g transform="translate(232,38)"><path d="M60,0L0,0L0,18C10,18 10,34 0,34L0,62h60Z" fill="#FCEFDD" stroke="#DE9A34" strokeWidth="2" strokeLinejoin="round"/><path d="M14,10q8,6 16,0t16,0M14,25q8,6 16,0t16,0M14,50q8,6 16,0t16,0" stroke="#B87A1F" strokeWidth="1.4" fill="none" opacity=".55"/></g><text x="262" y="122" textAnchor="middle" fontFamily="IBM Plex Mono" fontSize="10" fill="#5B655F">{target} binding pocket</text><circle className="dock-pulse" cx="238" cy="69" r="9" fill="none" stroke="#1F6F63" strokeWidth="2"/><g className="dock-molecule" key={replay}><path d="M0,0h60v18c10,0 10,16 0,16v28H0Z" fill="#1F6F63" stroke="#0F4A41" strokeWidth="2" strokeLinejoin="round" transform="translate(120,38)"/><polygon points="138,58 148,53 158,58 158,70 148,75 138,70" fill="none" stroke="#CDEBE1" strokeWidth="1.6"/><line x1="148" y1="53" x2="148" y2="44" stroke="#CDEBE1" strokeWidth="1.6"/><line x1="158" y1="58" x2="167" y2="53" stroke="#CDEBE1" strokeWidth="1.6"/></g><text x="150" y="122" textAnchor="middle" fontFamily="IBM Plex Mono" fontSize="10" fill="#5B655F">{result?.drug?.name || 'aspirin'}</text></svg><button className="btn btn-ghost replay-button" onClick={() => setReplay((value) => value + 1)}>↻ Replay docking</button></div>;
}

function ResultPage({ result, navigate }) {
  if (!result) return <div className="page active"><section className="page-intro"><Eyebrow>Sample output</Eyebrow><h2>No prediction yet</h2><p className="lede">Run a prediction on the “Try the predictor” page to see a live result here.</p><ActionButton onClick={() => navigate('Try the predictor')}>Go to Try the predictor →</ActionButton></section></div>;
  return <div className="page active"><section className="page-intro"><Eyebrow>Sample output</Eyebrow><h2>{result.drug.name} × {result.target.name} — prediction</h2><p className="lede">This is what a finished prediction looks like: the score, what it means in plain terms, and why the model reached it.</p></section><DockingScene result={result}/><div className="gauge-wrap"><div className="gauge-top"><div className="gauge-score">{result.score.toFixed(2)} <span>predicted KIBA score</span></div><div className="gauge-label">{result.label}</div></div><div className="gauge-track"><div className="gauge-marker" style={{ left: `${result.gauge_percent}%` }}/></div><div className="gauge-scale"><span>Weak</span><span>Moderate</span><span>Strong</span></div><p className="result-copy">{result.explanation}</p></div>{result.uncertainty !== null && <div className="uncertainty">GPR predictive uncertainty (std dev): ±{result.uncertainty.toFixed(3)}</div>}<section><Eyebrow>Why the model said this</Eyebrow><div className="reason-list">{result.features.map((feature) => <div className="reason" key={feature.technical_name}><div className={`bar ${feature.direction === 'positive' ? 'pos' : 'neg'}`}/><div className="rtext"><b>{feature.value >= 0 ? '+' : '−'}{Math.abs(feature.value).toFixed(2)}&nbsp;&nbsp;{feature.name}</b><span>{feature.explanation}</span></div></div>)}</div></section><div className="mini-note result-note"><span>ⓘ</span><span>Reasons are generated using SHAP values mapped to human-readable feature names from the featurizer.</span></div></div>;
}

function SciencePage({ benchmarks }) { const data = benchmarks || []; const best = (key, direction) => { const values = data.map((item) => Number(item[key])); return direction === 'min' ? Math.min(...values) : Math.max(...values); }; return <div className="page active"><section className="page-intro"><Eyebrow>For evaluators &amp; the curious</Eyebrow><h2>How the models actually compare</h2><p className="lede">Full results across all four algorithms, reported honestly across three evaluation splits.</p></section><div className="table-wrap"><table><thead><tr><th>Algorithm</th><th>Split</th><th>RMSE ↓</th><th>Concordance Index ↑</th><th>Pearson r ↑</th></tr></thead><tbody>{data.map((row) => <tr key={`${row.Split}-${row.Algorithm}`}><td>{row.Algorithm}</td><td><span className="split-tag">{row.Split.replace(' Split (Baseline)', '').toLowerCase()}</span></td><td className={Number(row.RMSE) === best('RMSE', 'min') ? 'best' : ''}>{Number(row.RMSE).toFixed(3)}</td><td className={Number(row.CI) === best('CI', 'max') ? 'best' : ''}>{Number(row.CI).toFixed(3)}</td><td className={Number(row['Pearson r']) === best('Pearson r', 'max') ? 'best' : ''}>{Number(row['Pearson r']).toFixed(3)}</td></tr>)}</tbody></table></div><section><Eyebrow>The honest headline</Eyebrow><div className="card headline-card"><h3>Every model gets worse on cold splits — and that's the finding, not a flaw</h3><p>All four algorithms score noticeably lower once drug or protein overlap is removed between train and test. That gap is the real story: it shows how much of a “good-looking” result on a random split was actually just memorized similarity, not genuine generalization.</p></div></section></div>; }

function AboutPage() { const team = [['A', 'Data & Drug Features', 'Dataset cleaning, split design, fingerprint & descriptor pipeline.'], ['B', 'Protein Features & Models', 'Protein feature pipeline, training and tuning all four algorithms.'], ['C', 'Evaluation & Interpretability', 'Metrics, SHAP analysis, pharmacophore sanity checks.'], ['D', 'App & Paper', 'Web app build, IEEE paper compilation, presentation.']]; return <div className="page active"><section className="page-intro"><Eyebrow>VTU Major Project</Eyebrow><h2>About this project</h2><p className="lede">DTI-ML predicts kinase drug-target binding affinity using classical machine learning, evaluated under a cold-split protocol and explained with SHAP feature attribution, built on the public KIBA benchmark.</p></section><div className="team-grid">{team.map(([letter, title, desc]) => <div className="member" key={title}><div className="avatar">{letter}</div><h3>{title}</h3><p>{desc}</p></div>)}</div><section><Eyebrow>References this project builds on</Eyebrow><p className="lede">Positioned against DeepDTA, GraphDTA, KronRLS, and SimBoost — comparing classical, feature-engineered ML against deep-learning DTI approaches on the same benchmark.</p></section></div>; }

function ChatWidget({ result }) { const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [messages, setMessages] = useState([{ role: 'bot', text: 'Hi — I can explain any term or number on this page in plain English. Tap a question below, or type your own.' }]); const [busy, setBusy] = useState(false); const send = async (preset = '') => { const value = (preset || question).trim(); if (!value || busy) return; setQuestion(''); setMessages((current) => [...current, { role: 'user', text: value }, { role: 'typing', text: '' }]); setBusy(true); try { const answer = await postJson('/api/chat', { question: value, context: result || {} }); setMessages((current) => [...current.filter((message) => message.role !== 'typing'), { role: 'bot', text: answer.answer }]); } catch { setMessages((current) => [...current.filter((message) => message.role !== 'typing'), { role: 'bot', text: 'I could not reach the explanation service just now — try again in a moment.' }]); } finally { setBusy(false); } }; return <><button className="chat-launcher" onClick={() => setOpen((value) => !value)} aria-label="Ask about this result"><svg width="24" height="24" viewBox="0 0 24 24" fill="none"><path d="M4 5h16v11H8l-4 4V5z" stroke="#fff" strokeWidth="1.8" strokeLinejoin="round"/></svg></button>{open && <div className="chat-panel"><div className="chat-head"><div><h4>Ask about this result</h4><span>{result ? 'grounded to your current prediction' : 'run a prediction for grounded answers'}</span></div><button className="chat-close" onClick={() => setOpen(false)} aria-label="Close chat">×</button></div><div className="chat-body">{messages.map((message, index) => message.role === 'typing' ? <div className="chat-typing" key={index}><i/><i/><i/></div> : <div className={`chat-msg ${message.role}`} key={index}>{message.text}</div>)}</div><div className="chat-suggest">{result && <button className="chip" onClick={() => send('What does this score mean?')}>What does this score mean?</button>}<button className="chip" onClick={() => send('Why lower on cold split?')}>Why lower on cold split?</button><button className="chip" onClick={() => send('Explain SHAP simply')}>Explain SHAP simply</button></div><form className="chat-inputrow" onSubmit={(event) => { event.preventDefault(); send(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a question..." aria-label="Ask a question"/><button type="submit">Send</button></form></div>}</>; }

function App() { const [page, setPage] = useState('Home'); const [result, setResult] = useState(null); const [presets, setPresets] = useState(fallbackPresets); const [benchmarks, setBenchmarks] = useState([]); useEffect(() => { getJson('/api/presets').then(setPresets).catch(() => {}); getJson('/api/benchmarks').then(setBenchmarks).catch(() => {}); }, []); const navigate = (next) => { setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }); }; return <><header><div className="nav-wrap"><a className="brand" href="#home" onClick={(event) => { event.preventDefault(); navigate('Home'); }}><BrandMark/><div><div className="brand-text">DTI-ML</div><div className="brand-sub">binding affinity predictor</div></div></a><nav aria-label="Primary navigation">{pages.map((item) => <button className={`navlink ${page === item ? 'active' : ''}`} key={item} onClick={() => navigate(item)}>{item}</button>)}</nav></div></header><main>{page === 'Home' && <HomePage navigate={navigate}/>} {page === 'How it works' && <HowPage/>} {page === 'Try the predictor' && <PredictorPage presets={presets} onPrediction={setResult} navigate={navigate}/>} {page === 'Sample result' && <ResultPage result={result} navigate={navigate}/>} {page === 'Model & science' && <SciencePage benchmarks={benchmarks}/>} {page === 'About' && <AboutPage/>}</main><footer>DTI-ML · VTU Major Project · production interface</footer><ChatWidget result={result}/></>; }

createRoot(document.getElementById('root')).render(<App/>);
